param([string]$Action, [string]$Target)
$ErrorActionPreference = "Stop"
Add-Type @'
using System; using System.Runtime.InteropServices;
public static class VeloCred { [StructLayout(LayoutKind.Sequential, CharSet=CharSet.Unicode)] public struct CREDENTIAL { public UInt32 Flags; public UInt32 Type; public string TargetName; public string Comment; public System.Runtime.InteropServices.ComTypes.FILETIME LastWritten; public UInt32 CredentialBlobSize; public IntPtr CredentialBlob; public UInt32 Persist; public UInt32 AttributeCount; public IntPtr Attributes; public string TargetAlias; public string UserName; } [DllImport("advapi32", CharSet=CharSet.Unicode, SetLastError=true)] public static extern bool CredWrite(ref CREDENTIAL credential, UInt32 flags); [DllImport("advapi32", CharSet=CharSet.Unicode, SetLastError=true)] public static extern bool CredRead(string target, UInt32 type, UInt32 flags, out IntPtr credential); [DllImport("advapi32", SetLastError=true)] public static extern bool CredDelete(string target, UInt32 type, UInt32 flags); [DllImport("advapi32")] public static extern void CredFree(IntPtr buffer); }
'@
if ($Action -eq "save") { $value = [Console]::In.ReadToEnd(); $bytes = [Text.Encoding]::Unicode.GetBytes($value); $ptr = [Runtime.InteropServices.Marshal]::AllocCoTaskMem($bytes.Length); [Runtime.InteropServices.Marshal]::Copy($bytes,0,$ptr,$bytes.Length); try { $credential = New-Object VeloCred+CREDENTIAL; $credential.Type=1; $credential.TargetName=$Target; $credential.CredentialBlobSize=$bytes.Length; $credential.CredentialBlob=$ptr; $credential.Persist=2; $credential.UserName="Velo"; if (-not [VeloCred]::CredWrite([ref]$credential,0)) { throw "CredWrite failed" } } finally { [Runtime.InteropServices.Marshal]::FreeCoTaskMem($ptr) } }
elseif ($Action -eq "has") { $ptr=[IntPtr]::Zero; $ok=[VeloCred]::CredRead($Target,1,0,[ref]$ptr); if($ok){[VeloCred]::CredFree($ptr); "true"}else{"false"} }
elseif ($Action -eq "read") { $ptr=[IntPtr]::Zero; $ok=[VeloCred]::CredRead($Target,1,0,[ref]$ptr); if($ok){try{$credential=[Runtime.InteropServices.Marshal]::PtrToStructure($ptr,[type][VeloCred+CREDENTIAL]); if($credential.CredentialBlob -ne [IntPtr]::Zero -and $credential.CredentialBlobSize -gt 0){$bytes=New-Object byte[] $credential.CredentialBlobSize; [Runtime.InteropServices.Marshal]::Copy($credential.CredentialBlob,$bytes,0,$credential.CredentialBlobSize); [Text.Encoding]::Unicode.GetString($bytes)}}finally{[VeloCred]::CredFree($ptr)}} }
elseif ($Action -eq "remove") { [void][VeloCred]::CredDelete($Target,1,0) }
