import { useEffect, useRef, useState } from "react";
import { ArrowCounterClockwise, Pause, Play } from "@phosphor-icons/react";

function sample(track, time) { if (!track?.times?.length) return null; let index = track.times.findIndex((item) => item >= time); if (index < 0) index = track.times.length - 1; if (!index) return Object.fromEntries(Object.entries(track).map(([key, value]) => [key, Array.isArray(value) ? value[0] : value])); const a = index - 1; const ratio = (time - track.times[a]) / (track.times[index] - track.times[a]); const value = (key) => !track[key]?.length ? undefined : track[key][a] + (track[key][index] - track[key][a]) * ratio; return { x: value("x"), y: value("y"), vx: value("vx"), vy: value("vy"), ax: value("ax"), ay: value("ay"), force_x: value("force_x"), force_y: value("force_y"), kinetic_energy: value("kinetic_energy"), potential_energy: value("potential_energy"), momentum_x: value("momentum_x"), momentum_y: value("momentum_y") }; }

export default function InteractivePanel({ timeline, onParameters }) {
  const canvasRef = useRef(null); const [time, setTime] = useState(0); const [playing, setPlaying] = useState(false); const [rate, setRate] = useState(1); const ids = Object.keys(timeline.scene?.objects || {}); const [selected, setSelected] = useState(ids[0] || ""); const duration = timeline.duration || 1;
  useEffect(() => { setTime(0); setPlaying(false); setSelected(ids[0] || ""); }, [timeline]);
  useEffect(() => { const canvas = canvasRef.current; if (!canvas) return; const draw = () => { const ctx = canvas.getContext("2d"); const rect = canvas.getBoundingClientRect(); const dpr = devicePixelRatio || 1; canvas.width = rect.width * dpr; canvas.height = rect.height * dpr; const [w, h] = timeline.scene.size || [800, 500]; const scale = Math.min(canvas.width / w, canvas.height / h); ctx.fillStyle = timeline.scene.background || "#fff"; ctx.fillRect(0, 0, canvas.width, canvas.height); for (const id of ids) { const state = sample(timeline.tracks[id], time); const object = timeline.scene.objects[id]; if (!state) continue; ctx.fillStyle = object.color || "#378ADD"; ctx.beginPath(); ctx.arc(state.x * scale, canvas.height - state.y * scale, Math.max(5, (object.radius || 10) * scale), 0, Math.PI * 2); ctx.fill(); } }; draw(); }, [timeline, time, ids]);
  useEffect(() => { if (!playing) return; let previous; let frame; const tick = (now) => { if (previous) setTime((value) => Math.min(duration, value + ((now - previous) / 1000) * rate)); previous = now; frame = requestAnimationFrame(tick); }; frame = requestAnimationFrame(tick); return () => cancelAnimationFrame(frame); }, [playing, duration, rate]);
  useEffect(() => { if (time >= duration) setPlaying(false); }, [time, duration]);
  const current = sample(timeline.tracks[selected], time); const values = [["Position", current && `${current.x?.toFixed(1)}, ${current.y?.toFixed(1)}`], ["Velocity", current && `${current.vx?.toFixed(1)}, ${current.vy?.toFixed(1)}`], ["Acceleration", current && `${current.ax?.toFixed(1)}, ${current.ay?.toFixed(1)}`], ["Force", current && `${current.force_x?.toFixed(1)}, ${current.force_y?.toFixed(1)}`], ["Kinetic energy", current?.kinetic_energy], ["Potential energy", current?.potential_energy], ["Momentum", current && `${current.momentum_x?.toFixed(1)}, ${current.momentum_y?.toFixed(1)}`]].filter(([, value]) => value !== undefined);
  return <section className="interactive-panel"><canvas ref={canvasRef} role="img" aria-label={timeline.scene?.title || "Interactive physics timeline"} /><div className="timeline-controls"><button onClick={() => setPlaying(!playing)} aria-label={playing ? "Pause simulation" : "Play simulation"}>{playing ? <Pause weight="fill" /> : <Play weight="fill" />}</button><button onClick={() => { setPlaying(false); setTime(0); }} aria-label="Restart simulation"><ArrowCounterClockwise weight="bold" /></button><input aria-label="Timeline position" type="range" min="0" max={duration} step="0.01" value={time} onChange={(event) => setTime(Number(event.target.value))} /><select aria-label="Playback speed" value={rate} onChange={(event) => setRate(Number(event.target.value))}><option value="0.5">0.5×</option><option value="1">1×</option><option value="2">2×</option></select></div><div className="inspect-panel"><strong>Inspect</strong><select value={selected} onChange={(event) => setSelected(event.target.value)} aria-label="Object to inspect">{ids.map((id) => <option key={id}>{id}</option>)}</select>{values.map(([label, value]) => <span key={label}><b>{label}</b> {typeof value === "number" ? value.toFixed(2) : value}</span>)}</div>{timeline.parameters?.length > 0 && <div className="parameter-panel"><strong>Parameters</strong>{timeline.parameters.map((parameter) => <label key={parameter.id}>{parameter.id}<input type="number" defaultValue={parameter.default} min={parameter.minimum} max={parameter.maximum} onBlur={(event) => onParameters({ [parameter.id]: Number(event.target.value) })} /></label>)}</div>}</section>;
}
